# Generated by Django 4.1.6 on 2026-04-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
